/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CategoriaTransformer from '#transformers/categoria_transformer'
import type FilmeTransformer from '#transformers/filme_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Categoria = InferData<CategoriaTransformer>
  export namespace Categoria {
    export type Variants = InferVariants<CategoriaTransformer>
  }
  export type Filme = InferData<FilmeTransformer>
  export namespace Filme {
    export type Variants = InferVariants<FilmeTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
